import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { defineConfig } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
	server: {
		port: 3000,
	},
	esbuild: {
		target: "esnext",
	},
	build: {
		target: "esnext",
	},
	plugins: [
		tailwindcss(),
		tsConfigPaths({
			projects: ["./tsconfig.json"],
		}),
		tanstackStart({
			target: "bun",
			tsr: {
				routeTreeFileHeader: [
					"/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
				],
				quoteStyle: "double",
			},
		}),
	],
});
